# docker-compose -f docker-compose.test.yml build 
# docker-compose -f docker-compose.test.yml up -d 
# docker exec -it go-rails-rails-test-1 sh
# docker-compose -f docker-compose.test.ym down
# docker network prune -f
# docker volume prune -f
version: '3.8'

services:
  rails-test:
    image: go-rails/test
    build:
      context: .
      dockerfile: ./Dockerfile.test
    container_name: go-rails-test
    tty: true
    volumes:
      - ./:/go-ethereum 